name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      env:
        ingestionURI : ${{secrets.INGEST_ENDPOINT}}
        databaseName : ${{secrets.DATABASE}}
        appId : ${{secrets.APP_ID}}
        appKey : ${{secrets.APP_KEY}}
        tenant : ${{secrets.AZURE_TENANT_ID}}
      run: dotnet test src --no-build --verbosity normal
